#!/usr/bin/env php
<?php

include_once __DIR__ . '/vendor/autoload.php';

use Packagist\Api\Result\Package\Version;
use GitWrapper\GitWrapper;

$version_overrides = array();
if (file_exists(__DIR__.'/version_overrides.php')) {
	$version_overrides = include __DIR__.'/version_overrides.php';
}

echo "\n";

$options = getopt('f:o:', array(
	'check-git',			// do we check whether the master branch is different from latest tag?
	'modules::',			// which modules should we inspect?
	'readme::',				// should we generate a collation of 'readme' files?
	'ssau',
	'version-fix::',		// do we output a list of 'fixed' versions for the modules based on packagist info?
	'timeout::',
	'workspace::'			// what folder to use as the 'workspace' for checking out data into?
));

$client = new Packagist\Api\Client();
$composerFiles = array();
$modules = array();

// Determine whether there is a "composer.json" to check against.

if(isset($options['f'])) {
	$file = realpath($options['f']);
	if(!file_exists($file)) {
		usage();
		o("Could not read $file\n");
		exit();
	}
	$composer = json_decode(file_get_contents($file));
	if(!$composer) {
		usage();
		o("Could not find composer details\n");
		exit();
	}
	$composerFiles = array($file);

	// Determine whether any further modules have been defined to check against.

	if(isset($options['modules']) && $options['modules']) {
		$modules = explode(',', $options['modules']);
		foreach($modules as $module) {
			$project = dirname($file);
			$moduleComposer = "{$module}/composer.json";
			$moduleComposerPath = "{$project}/{$moduleComposer}";

			if(!file_exists($moduleComposerPath)) {
				o("Could not read/parse {$moduleComposerPath}");
				continue;
			}
			$composerFiles[] = $moduleComposerPath;
		}
	}
}
else if(isset($options['o']) && $options['o']) {

	// There is no "composer.json", therefore check against specific packagist owner modules.

	$owners = explode(',', $options['o']);
	foreach($owners as $owner) {
		$modules = array_merge($modules, $client->all(array(
			'vendor' => trim($owner)
		)));
	}

	// Determine whether the core SSAU supported packagist modules should be included.

	if(isset($options['ssau']) && file_exists(__DIR__ . '/SSAU_supported_modules.php')) {
		$other = include __DIR__ . '/SSAU_supported_modules.php';
		$modules = array_merge($modules, $other);
	}

	// The following is used to determine whether a "composer.json" was provided.

	if(count($modules)) {
		$composerFiles = array(null);
	}
}
else {

	// Something needs to be provided, otherwise there's nothing to check.

	usage();
	exit();
}

$workspace = isset($options['workspace']) ? $options['workspace'] : __DIR__ . '/workspace';

$wrapper = new GitWrapper();
$time = isset($options['timeout']) ? intval($options['timeout']) : 120;
$wrapper->setTimeout($time);

$notices = array();
$URLs = array();

$allRequirements = array();
$readmeContents = array();

foreach ($composerFiles as $composerFile) {

	// The following is used to determine whether a "composer.json" was provided.

	if($composerFile) {
		$composer = json_decode(file_get_contents($composerFile));
		$packages = $composer->require;
	}
	else {
		$packages = array_flip($modules);

		// The modules that we can ignore, since they're abandoned.

		$ignored = array(
			'silverstripe-australia/intranet-sis',
			'silverstripe-australia/salesforce-auth',
			'silverstripe-australia/silverstripe-pagejax',
			'silverstripe-australia/vuforia',
			'silverstripe-australia/wordpressconnector'
		);
		foreach($ignored as $ignore) {
			unset($packages[$ignore]);
		}

		// Use a base required version to check against.

		foreach($packages as $package => $temporary) {
			$packages[$package] = 'dev-master';
		}
	}
	foreach ($packages as $packageName => $requiredVersion) {
		if($packageName === 'php') {
			continue;
		}
		$package_name = basename($packageName);

		// Retrieve the module from packagist.

		$package = retrieve_package($packageName, $requiredVersion, $client, $options);
		if(!$package) {
			continue;
		}

		$latestVersion = 0;
		$repo = null;
		$latestRef = null;
		$tip = null;

		foreach ($package->getVersions() as $branch => $version) {
			if($branch === 'dev-master') {
				$tip = $version->getSource()->getReference();
			}
			/* @var $version Version */
			$source = $version->getSource();

			$comp = version_compare($version->getVersion(), $latestVersion);
	//		o("Comparing " . $version->getVersion() . " to $latestVersion : $comp");
			if (version_compare($version->getVersion(), $latestVersion) > 0) {
				$latestVersion = $version->getVersion();
				$repo = $version->getSource()->getUrl();
				$latestRef = $version->getSource()->getReference();
			}
			if (!$latestRef) {
				$latestRef = $version->getSource()->getReference();
			}
		}

		// Determine whether this repository actually belongs to SSAU, otherwise skip it.

		if(isset($options['o']) && isset($options['ssau']) && (strpos($repo, '/silverstripe-australia/') === false)) {
			continue;
		}

		$allRequirements[$packageName] = $latestVersion;

		if (!isset($options['o']) && (version_compare($latestVersion, $requiredVersion) > 0) && $latestVersion) {
			$notices[] = "\033[31m✘ $packageName has an updated, fixed tag version available $latestVersion (currently $requiredVersion)\033[0m";
		} else if (!isset($options['o']) && $latestVersion) {
			$notices[] = "\033[32m✔ $packageName looks to be using the latest available version\033[0m";
		} else if (!$latestVersion) {

			$notices[] = "\033[0;36m✘ $packageName has no proper version available\033[0m";
		}

		// now check out the project
		if ($repo && $latestRef && (isset($options['check-git']) || isset($options['readme']))) {
			$path = $workspace . DIRECTORY_SEPARATOR . basename($package_name);
			if (!file_exists($path)) {
				$git = $wrapper->cloneRepository($source->getUrl(), $path);
				$git->checkout('master', array('f' => true));
			} else {
				$git = $wrapper->workingCopy($path);
				$git->checkout('master', array('f' => true));
				$git->pull();
				$git->fetch(array('tags' => true));
			}

			$git->clearOutput();
			// checkout the 'latest' ref as far as packagist knows about, then check to see
			// whether the repository has changes between it and the current master HEAD
			// $git->diff($latestRef, array('name-status' => true));
			$git->log($latestRef . '..master', array('pretty' => 'oneline', 'abbrev-commit' => true));
			$out = trim($git->getOutput());

			if (isset($options['check-git'])) {
				if (strlen($out)) {
					$lines = explode("\n", $out);
					if (count($lines) > 0) {
						$notices[] = "\033[31m✘ $packageName: " . count($lines) . " commits found between $latestVersion ($latestRef) and master\033[0m\n";
						$URL = substr($repo, 0, -4);
						$URLs[] = "* {$URL}/commit/{$tip}";
					}
				} else {
					$notices[] = "\033[32m✔ $packageName @ $latestVersion appears to be up-to-date\033[0m\n";
				}
			}
			if (isset($options['readme'])) {
				if (file_exists($path . '/README.md')) {
					$readmeContents[$package_name] = file_get_contents($path . '/README.md');
				}
			}
		}

		// This is to space things out correctly when "check-git" is not being used.

		else {
			$notices[] = "";
		}
	}
}

foreach ($notices as $notice) {
	o($notice);
}

if(count($URLs)) {
	foreach ($URLs as $URL) {
		o($URL);
	}
	echo "\n";
}

if(isset($options['version-fix']) && $options['version-fix']) {
	o("Recommended project composer requirements: \n");
	foreach ($allRequirements as $package => $version) {
		o("\t\t" . '"' . $package . '": "' . $version . '",');
	}
	o('');
}

if (count($readmeContents)) {
	$dir = 'readme';
	if (isset($options['readme']) && is_string($options['readme']) && strlen($options['readme']) > 1) {
		$dir = $options['readme'];
	}

	if ($dir{0} != '/') {
		$dir = $workspace . '/' . $dir;
	}
	if (is_bool($dir)) {
		exit("Something's busted");
	}
	if (is_dir($dir)) {
		del_tree($dir);
	}
	mkdir($dir);

	$p = new ParsedownExtra();
	$links = array();
	foreach ($readmeContents as $name => $content) {
		$outfile = $dir . '/' . $name . '.html';
		$content = $p->text($content);
		file_put_contents($outfile, $content);
		$links[] = $name;
	}

	$indexContent = '';
	foreach ($links as $link) {
		$indexContent .= "* [$link]($link.html)\n";
	}
	$indexContent = $p->text($indexContent);
	file_put_contents($dir .'/index.html', $indexContent);
}

function o($txt) {
	echo "$txt\n";
}

function retrieve_package($packageName, $requiredVersion, $client, $options) {
	try {
		$package = $client->get($packageName);
	}
	catch(Exception $e) {
		o("\033[31m✘ The package could not be found\n\033[0m");
		return false;
	}

	if(!isset($options['o'])) {
		o("Retrieved package " . $package->getName() . "\n");
	}
	return $package;
}

function del_tree($dir) {
	$files = array_diff(scandir($dir), array('.', '..'));
	foreach ($files as $file) {
		(is_dir("$dir/$file") && !is_link($dir)) ? del_tree("$dir/$file") : unlink("$dir/$file");
	}
	return rmdir($dir);
}

function usage() {
	o("Please either provide a \"-f composer.json\" or \"-o packagist,owners\"");
	o("The options for configuration can be found in the documentation.\n");
}
